version: '3.9'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod-build
      args:
        - VITE_GA_ID=${VITE_GA_ID}
        - VITE_GA_DEBUG=${VITE_GA_DEBUG}
    image: application:latest
    hostname: application
    restart: always
    ports:
      - "8080:8080"
  db:
    hostname: db
    image: ankane/pgvector
    ports:
      - 6543:5432
    restart: always
    environment:
      - POSTGRES_DB=learn-rag-database
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
