/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */

export type AutoMergingSearchParams = {
  query: string;
  chunkSize: number;
  chunkOverlap: number;
  childChunkSize: number;
  childChunkOverlap: number;
  limit: number;
  childParentPrevalenceFactor: number;
};
