/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */
import type { AutoMergingEmbeddingOptions } from "./autoMergingEmbeddingOptions";

export type AutoMergingMetadata = {
  documentId?: string;
  embeddingOptions?: AutoMergingEmbeddingOptions;
  index?: number;
  /** @nullable */
  parentIndex?: number | null;
};
