/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */
import type { SingleReadOnlyMemory } from "./singleReadOnlyMemory";
import type { AutoMergingMetadata } from "./autoMergingMetadata";

export type AutoMergingMetadataEmbeddingRecord = {
  embedding?: SingleReadOnlyMemory;
  id?: string;
  metadata?: AutoMergingMetadata;
  /** @nullable */
  text?: string | null;
};
