/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */
import type { SingleReadOnlyMemory } from "./singleReadOnlyMemory";
import type { BasicMetadata } from "./basicMetadata";

export type BasicMetadataEmbeddingRecord = {
  embedding?: SingleReadOnlyMemory;
  id?: string;
  metadata?: BasicMetadata;
  /** @nullable */
  text?: string | null;
};
