/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */
import type { BasicMetadata } from "./basicMetadata";

export type BasicMetadataSearchResult = {
  id?: string;
  metadata?: BasicMetadata;
  /** @nullable */
  relevance?: number | null;
  /** @nullable */
  text?: string | null;
};
