/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */
import type { BasicEmbeddingOptions } from "./basicEmbeddingOptions";

export type BasicMetadata = {
  documentId?: string;
  embeddingOptions?: BasicEmbeddingOptions;
  index?: number;
};
