/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */
import type { HierarchicalMetadata } from "./hierarchicalMetadata";

export type HierarchicalMetadataSearchResult = {
  id?: string;
  metadata?: HierarchicalMetadata;
  /** @nullable */
  relevance?: number | null;
  /** @nullable */
  text?: string | null;
};
