/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */
import type { HierarchicalEmbeddingOptions } from "./hierarchicalEmbeddingOptions";

export type HierarchicalMetadata = {
  documentId?: string;
  embeddingOptions?: HierarchicalEmbeddingOptions;
  index?: number;
  /** @nullable */
  parentIndex?: number | null;
  /** @nullable */
  summary?: string | null;
};
