/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */
import type { HypotheticalQuestionMetadata } from "./hypotheticalQuestionMetadata";

export type HypotheticalQuestionMetadataSearchResult = {
  id?: string;
  metadata?: HypotheticalQuestionMetadata;
  /** @nullable */
  relevance?: number | null;
  /** @nullable */
  text?: string | null;
};
