/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */

export type HypotheticalQuestionEmbeddingOptions = {
  chunkOverlap?: number;
  chunkSize?: number;
  numberOfQuestions?: number;
};
