/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */
import type { SingleReadOnlyMemory } from "./singleReadOnlyMemory";
import type { HypotheticalQuestionMetadata } from "./hypotheticalQuestionMetadata";

export type HypotheticalQuestionMetadataEmbeddingRecord = {
  embedding?: SingleReadOnlyMemory;
  id?: string;
  metadata?: HypotheticalQuestionMetadata;
  /** @nullable */
  text?: string | null;
};
