/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */
import type { HypotheticalQuestionEmbeddingOptions } from "./hypotheticalQuestionEmbeddingOptions";

export type HypotheticalQuestionMetadata = {
  documentId?: string;
  embeddingOptions?: HypotheticalQuestionEmbeddingOptions;
  index?: number;
  /** @nullable */
  questions?: string[] | null;
};
