/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */
import type { SingleReadOnlyMemory } from "./singleReadOnlyMemory";
import type { SentenceWindowMetadata } from "./sentenceWindowMetadata";

export type SentenceWindowMetadataEmbeddingRecord = {
  embedding?: SingleReadOnlyMemory;
  id?: string;
  metadata?: SentenceWindowMetadata;
  /** @nullable */
  text?: string | null;
};
