/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */
import type { SentenceWindowEmbeddingOptions } from "./sentenceWindowEmbeddingOptions";

export type SentenceWindowMetadata = {
  documentId?: string;
  embeddingOptions?: SentenceWindowEmbeddingOptions;
  index?: number;
  /** @nullable */
  originalText?: string | null;
};
