/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */
import type {
  GetSentenceWindowEmbeddingOptionsParams,
  SentenceWindowEmbeddingOptions,
  SentenceWindowMetadataEmbeddingRecord,
  SentenceWindowMetadataSearchResult,
  SentenceWindowPreviewParams,
  SentenceWindowSearchParams,
} from "../../model";
import getSentenceWindowEmbeddingOptionsMutator from "../../axios";
import sentenceWindowSearchMutator from "../../axios";
import sentenceWindowPreviewMutator from "../../axios";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const getSentenceWindowEmbeddingOptions = (
  params: GetSentenceWindowEmbeddingOptionsParams,
  options?: SecondParameter<typeof getSentenceWindowEmbeddingOptionsMutator>
) => {
  return getSentenceWindowEmbeddingOptionsMutator<SentenceWindowEmbeddingOptions[]>(
    { url: `/api/sentence-window/embedding-options`, method: "GET", params },
    options
  );
};
export const sentenceWindowSearch = (
  params: SentenceWindowSearchParams,
  options?: SecondParameter<typeof sentenceWindowSearchMutator>
) => {
  return sentenceWindowSearchMutator<SentenceWindowMetadataSearchResult[]>(
    { url: `/api/sentence-window/search`, method: "GET", params },
    options
  );
};
export const sentenceWindowPreview = (
  params: SentenceWindowPreviewParams,
  options?: SecondParameter<typeof sentenceWindowPreviewMutator>
) => {
  return sentenceWindowPreviewMutator<SentenceWindowMetadataEmbeddingRecord[]>(
    { url: `/api/sentence-window/preview`, method: "GET", params },
    options
  );
};
export type GetSentenceWindowEmbeddingOptionsResult = NonNullable<
  Awaited<ReturnType<typeof getSentenceWindowEmbeddingOptions>>
>;
export type SentenceWindowSearchResult = NonNullable<
  Awaited<ReturnType<typeof sentenceWindowSearch>>
>;
export type SentenceWindowPreviewResult = NonNullable<
  Awaited<ReturnType<typeof sentenceWindowPreview>>
>;
