/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */
import type {
  AutoMergingEmbeddingOptions,
  AutoMergingMetadataEmbeddingRecord,
  AutoMergingMetadataSearchResult,
  AutoMergingPreviewParams,
  AutoMergingSearchParams,
  GetAutoMergingEmbeddingOptionsParams,
} from "../../model";
import getAutoMergingEmbeddingOptionsMutator from "../../axios";
import autoMergingSearchMutator from "../../axios";
import autoMergingPreviewMutator from "../../axios";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const getAutoMergingEmbeddingOptions = (
  params: GetAutoMergingEmbeddingOptionsParams,
  options?: SecondParameter<typeof getAutoMergingEmbeddingOptionsMutator>
) => {
  return getAutoMergingEmbeddingOptionsMutator<AutoMergingEmbeddingOptions[]>(
    { url: `/learn-rag-api/auto-merging/embedding-options`, method: "GET", params },
    options
  );
};
export const autoMergingSearch = (
  params: AutoMergingSearchParams,
  options?: SecondParameter<typeof autoMergingSearchMutator>
) => {
  return autoMergingSearchMutator<AutoMergingMetadataSearchResult[]>(
    { url: `/learn-rag-api/auto-merging/search`, method: "GET", params },
    options
  );
};
export const autoMergingPreview = (
  params: AutoMergingPreviewParams,
  options?: SecondParameter<typeof autoMergingPreviewMutator>
) => {
  return autoMergingPreviewMutator<AutoMergingMetadataEmbeddingRecord[]>(
    { url: `/learn-rag-api/auto-merging/preview`, method: "GET", params },
    options
  );
};
export type GetAutoMergingEmbeddingOptionsResult = NonNullable<
  Awaited<ReturnType<typeof getAutoMergingEmbeddingOptions>>
>;
export type AutoMergingSearchResult = NonNullable<Awaited<ReturnType<typeof autoMergingSearch>>>;
export type AutoMergingPreviewResult = NonNullable<Awaited<ReturnType<typeof autoMergingPreview>>>;
