/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Learn RAG API
 * OpenAPI spec version: v1
 */
import type {
  GetHierarchicalEmbeddingOptionsParams,
  HierarchicalEmbeddingOptions,
  HierarchicalMetadataEmbeddingRecord,
  HierarchicalMetadataSearchResult,
  HierarchicalPreviewParams,
  HierarchicalSearchParams,
} from "../../model";
import getHierarchicalEmbeddingOptionsMutator from "../../axios";
import hierarchicalSearchMutator from "../../axios";
import hierarchicalPreviewMutator from "../../axios";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const getHierarchicalEmbeddingOptions = (
  params: GetHierarchicalEmbeddingOptionsParams,
  options?: SecondParameter<typeof getHierarchicalEmbeddingOptionsMutator>
) => {
  return getHierarchicalEmbeddingOptionsMutator<HierarchicalEmbeddingOptions[]>(
    { url: `/learn-rag-api/hierarchical/embedding-options`, method: "GET", params },
    options
  );
};
export const hierarchicalSearch = (
  params: HierarchicalSearchParams,
  options?: SecondParameter<typeof hierarchicalSearchMutator>
) => {
  return hierarchicalSearchMutator<HierarchicalMetadataSearchResult[]>(
    { url: `/learn-rag-api/hierarchical/search`, method: "GET", params },
    options
  );
};
export const hierarchicalPreview = (
  params: HierarchicalPreviewParams,
  options?: SecondParameter<typeof hierarchicalPreviewMutator>
) => {
  return hierarchicalPreviewMutator<HierarchicalMetadataEmbeddingRecord[]>(
    { url: `/learn-rag-api/hierarchical/preview`, method: "GET", params },
    options
  );
};
export type GetHierarchicalEmbeddingOptionsResult = NonNullable<
  Awaited<ReturnType<typeof getHierarchicalEmbeddingOptions>>
>;
export type HierarchicalSearchResult = NonNullable<Awaited<ReturnType<typeof hierarchicalSearch>>>;
export type HierarchicalPreviewResult = NonNullable<
  Awaited<ReturnType<typeof hierarchicalPreview>>
>;
